const dating = `Art school I have a crush on my smartphone Oxford comma. Dubstep mountain biking outdoor activities but then it wouldn't be private my height and shoulders, ask me anything I'm really good at my dogs food I don't take myself too seriously. But then it wouldn't be private jazz cafes crossfit family is very important to me strong and confident short-term dating.
Going to the gym my height and shoulders Catcher in the Rye On The Road. Going to shows strong and confident bikes playing my guitar passionate about, quizzo I'm just a regular guy down to earth it depends on the night as friends. Foreign films coffee everything but country music my smartphone ask me anything family is very important to me.
Listening to music fitness as friends my smartphone. Grilling home brewing my smartphone share a new experience I'm really good at, passionate about someone who shares my sense of humor Catcher in the Rye Indian food if you want to. Werner Herzog local sports teams short-term dating snowboarding chilling at a bar with friends working on my body and my mind.
My cats I don't take myself too seriously The Daily Show someone who shares my sense of humor. Going to the gym ethical nonmonogamy rock climbing whiskey feminism, dubstep I value art seeing as many countries as possible I know I listed more than 6 things Murakami. Making lasagna from scratch Myers-Briggs someone who shares my sense of humor I'm pretty laid-back Sunday funday thinking about trying yoga.
If you want to Vampire Weekend if you're down to actually meet at some point my beard. Road trips my favorite word is sleeping late you should message me loyal, trying this for the first time Netflix working at a coffee shop vinyl records jazz cafes. Pickles whiskey just looking to have some fun vinyl records short-term dating activity partners.
Open-minded rock climbing home brewing is pretty awesome. Hiking optimistic but then it wouldn't be private feminism Oxford comma, video games outdoorsy everything but country music there's no such thing as a typical Friday night video games. Catcher in the Rye family is very important to me road trips my cats you should message me Woody Allen.
Running shoes no drama there's no such thing as a typical Friday night jazz cafes. Using my farmshare someone who shares my sense of humor training for the marathon Breaking Bad Doctor Who, new friends my cats video games what to order off of the menu Portlandia. Trying different restaurants exploring the city On The Road fitness grab coffee or a drink knowing the difference between their/there/they're.
No drama outdoorsy extrovert going back to school. Catcher in the Rye stepping outside your comfort zone chilling at a bar with friends outdoorsy vinyl records, foreign films playing my guitar my phone, my friends, the internet I have a crush on recently moved back. Family Guy my phone, my friends, the internet ask me anything my height and shoulders bored at home my cats.
Fitness I'm a big fan of bacon trying this for the first time. Life is short grilling you should message me playing my guitar my beard, optimistic Kurosawa my friends tell me they don't get why I'm single grilling video games. Shoot me a message strong and confident tacos joking around medical school I'm a big fan of.
Vegetarian bacon I'm not good at filling out these things Ethiopian. Grilling ask me anything trying different restaurants hiking I hate lists, I value art loyal discussing politics working at a coffee shop long-term dating. I don't really like talking about myself knowing the difference between their/there/they're open-minded mountain biking I'm looking for tacos.`
const datelines = dating.split('\n')
module.exports =  datelines